### ISSUE TITLE
This package is not in the mvn repo?

### ISSUE THREAD

**Issue by MoonLord-LM** [apache/logging-log4j-jmx-gui#2] opened 2023-10-30 18:52 UTC
HTTP 404：
https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-jmx-gui/2.21.1/

**Comment by MoonLord-LM** [comment] 2023-10-30 19:00
<img width="1173" alt="Screenshot 2023-10-31 025833" src="https://github.com/apache/logging-log4j-jmx-gui/assets/8104133/4729d0f3-5a70-4dae-9751-3444d33752a0">

**Comment by MoonLord-LM** [comment] 2023-10-30 19:01
https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-bom/2.21.1

**Comment by ppkarwasz** [comment] 2023-10-30 19:07
@MoonLord-LM,

Thank you for the report. The problem is that `log4j-bom` contains a bad entry, so I am closing this issue and keeping apache/logging-log4j2#1926

**Closed by ppkarwasz** 2023-10-30 19:07 UTC
